name: "Buildkit state"
description: Load and save buildkit state.
inputs:
  buildx-name:
    required: true
    description: |
      Name of buildx. Required if `buildx_container_name` is not given.
      Fill as `name` output of `docker/setup-buildx-action` actions.
  cache-key:
    description: Github cache key.
    required: true
    default: ${{ runner.os }}-buildkit_state-${{ github.sha }}
  cache-restore-keys:
    description: Github cache restore key.
    required: true
    default: |
      ${{ runner.os }}-buildkit_state-
  target-types:
    description: '`regular` | `source.local` | `source.git.checkout` | `exec.cachemount` | `frontend` | `internal`'
    default: |
      exec.cachemount
      frontend
    required: true
  rewrite-cache:
    description: Whether to overwrite when the same cache key already exists
    default: "false"

runs:
  using: node16
  main: dist/restore/index.js
  post: dist/save/index.js
  post-if: success()
