FROM python:3.11 as builder
WORKDIR /app

COPY . .

RUN \
  --mount=type=cache,target=/root/.cache/pip \
  --mount=type=cache,target=/root/.cache/ccache \
    apt-get update -qq  \
    && apt-get install -y --no-install-recommends ccache \
    && pip install build  \
    && python -m build --wheel --outdir /dist  \
    && CC='ccache gcc' pip wheel /dist/*.whl -w /wheels --disable-pip-version-check --no-clean --use-pep517

FROM python:3.11-slim
ENTRYPOINT ["print_version"]

RUN \
  --mount=type=bind,target=/wheels,from=builder,source=/wheels \
  --mount=type=bind,target=/dist,from=builder,source=/dist \
    pip install \
      --no-index \
      --no-deps \
      --find-links=/wheels \
      /dist/*.whl
