run:
  timeout: 3m

output:
  sort-results: true

linters:
  enable:
    - gosec
    - bodyclose
    - containedctx
    - gofumpt
    - gci
    - errname
    - revive
    - lll
    - paralleltest
    - tparallel

linters-settings:
  gosec:
    excludes:
      - G401
  gofumpt:
    # Module path which contains the source code being formatted.
    # Default: ""
    module-path: github.com/isac322/buildkit-state/probe
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  gci:
    # Section configuration to compare against.
    # Section names are case-insensitive and may contain parameters in ().
    # The default order of sections is `standard > default > custom > blank > dot`,
    # If `custom-order` is `true`, it follows the order of `sections` option.
    # Default: ["standard", "default"]
    sections:
      - standard # Standard section: captures all standard packages.
      - prefix(github.com/isac322/buildkit-state/probe) # Custom section: groups all imports with the specified Prefix.
      - default # Default section: contains all imports that could not be matched to another section type.
#      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
#      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
    # Enable custom order of sections.
    # If `true`, make the section order the same as the order of `sections`.
    # Default: false
    custom-order: true

issues:
  exclude-rules:
    - path: '^(.+)_test\.go$'
      linters:
        - bodyclose
