name: Benchmark & Example

on:
  push:
    paths:
      - .github/workflows/benchmarks.yaml
  workflow_dispatch:

jobs:
  python-buildkit-first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore BuildKit state
        uses: isac322/buildkit-state@v2
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}
          cache-key: ${{ runner.os }}-buildkit_state-python
          cache-restore-keys: ''

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: example/python
          file: example/python/Dockerfile-buildkit-cache
          push: false

  python-buildkit-after-adding-new-dep:
    runs-on: ubuntu-latest
    needs: [python-buildkit-first]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Add a dependency
        working-directory: example/python
        # language=Bash
        run: |
          sed -Ei 's/(\w*"pydantic==.+?".*)/\1\n"arrow==1.2.3",/' pyproject.toml

      - name: Restore BuildKit state
        uses: isac322/buildkit-state@v2
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}
          target-types: ''
          cache-key: ${{ runner.os }}-buildkit_state-python-null
          cache-restore-keys: |
            ${{ runner.os }}-buildkit_state-python

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: example/python
          file: example/python/Dockerfile-buildkit-cache
          push: false

  python-vanilla-first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: example/python
          file: example/python/Dockerfile-no-cache
          push: false

  python-vanilla-after-adding-new-dep:
    runs-on: ubuntu-latest
    needs: [python-vanilla-first]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Add a dependency
        working-directory: example/python
        # language=Bash
        run: |
          sed -Ei 's/(\w*"pydantic==.+?".*)/\1\n"arrow==1.2.3",/' pyproject.toml

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: example/python
          file: example/python/Dockerfile-no-cache
          push: false
